# Spring Boot ?????? ??

# ?? ?? ??
server:
  port: 8080
  servlet:
    encoding:
      force-response: true

# ?????? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
    username: your-username
    password: your-password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: local # ?? ?? ??

# ?? ??
logging:
  level:
    root: info

# ????? ??
file:
  uploadPath: /Users/dongbisul/upload/